version: "3.1"

services:
   
   postgres_simple:
      image: postgres
      volumes:
      - postgres_data: $HOME/docker/volumes/postgres_simple:/var/lib/postgresql/data
      ports:
      - 5432:5432
      - 8080:8080
      environment:
      - POSTGRES_USER=Nikita
      - POSTGRES_PASSWORD=9492088
      - POSTGRES_DB=hello_django_dev
      restart: always


